### ISSUE TITLE
property "fillColor" isn't supported in 2.x version.

### ISSUE THREAD

**Issue by m1neral** [highslide-software/pattern-fill#12]
In the previous version 1.x it was possible to fill series established color and use pattern over the fill[property "fillColor"].

How to do it in the new version?
Thanks!

**Comment by h4ckm03d** [comment]
Hi @m1neral
Little bit different but more simple. e.g. I wan't to use pattern number 0
`color:'url(#highcharts-default-pattern-0)'`
or 
`fillColor:'url(#highcharts-default-pattern-0)'`

here an example http://jsfiddle.net/ErU8H/530/

**Comment by m1neral** [comment]
Hi @h4ckm03d

Thanks for the reply, but option "color" implemented in new version of plugin (by pull-request @stephanevanraes ). Issue was created in a previous version :)
