### ISSUE TITLE
pattern source files at highchart.com are not found

### ISSUE THREAD

**Issue by KacperMadej** [highslide-software/pattern-fill#7]
Site: http://www.highcharts.com/components/com_demo/views/demo/tmpl/demo/gfx/pattern1.png
Returns: Not Found

The requested URL /joomla/components/com_demo/views/demo/tmpl/demo/gfx/pattern1.png was not found on this server.

Same with both other pattern files.

**Comment by h4ckm03d** [comment]
@KacperMadej Instead using from that link, you can used your own image or image which included in this plugin.

**Comment by highslide-software** [comment]
Use pattern files from GitHub instead
